# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gen3_arm_cotroller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gen3_arm_cotroller:
  ros__parameters:
    joints:
      - gen3_joint_1
      - gen3_joint_2
      - gen3_joint_3
      - gen3_joint_4
      - gen3_joint_5
      - gen3_joint_6
      - gen3_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true